### ISSUE TITLE
scale_bar not found

### ISSUE THREAD

**Issue by hoehna** [cmt2/RevGadgets#4]
Just got the following issue:

plotTree(tree = tree , timeline = T, tip_labels_italics = F, tip_labels_remove_underscore = T, node_age_bars = T, node_age_bars_colored_by = "posterior", node_age_bars_color = rev(RevGadgets :::.colFun (2))) + ggplot2 ::theme(legend.position=c(.25,  .85))
Error in plotTree(tree = tree, timeline = T, tip_labels_italics = F, tip_labels_remove_underscore = T,  : 
  object 'scale_bar' not found

**Comment by cmt2** [comment]
This is now fixed in Development - i"ll do a general merge with master
after addressing your 'split tree' problem while plotting.
*_______________*

*Carrie Malina Tribble <http://carrietribble.weebly.com>*
*Integrative Biology PhD Candidate at UC Berkeley*
*Williams College '13, Biology and Environmental Studies*
